spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/energy_monitor_db
    username: energy_monitor
    password: energy_monitor_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
  mvc:
    apiVersion:
      use:
        header: x-api-v
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

logging:
  level:
    org.flywaydb : debug
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG



